### ISSUE TITLE
Problem on new install

### ISSUE THREAD

**Issue by coffeverton** [cronfig/mautic-cronfig#1]
Hi, 
when i try to install it in the plugin management section (item 7 on the installation guide), the register/login screen does not appear. It only shows the icon and description of the plugin.

Screen: http://screencloud.net/v/iL1T

I'm using the latest mautic version.

**Comment by escopecz** [comment]
Take a look at the installation instructions again, please. Especially the point 7.

https://github.com/cronfig/mautic-cronfig

**Comment by coffeverton** [comment]
Nevermind, now I got it.
I though that the register form should appear in the plugin management tool.

Thank you!
