### ISSUE TITLE
Error info: HTTP status is not 2xx. That means not successful. HTTP status: 403

### ISSUE THREAD

**Issue by escopecz** [cronfig/mautic-cronfig#3]
I'm self-reporting this issue because I run out of ideas what is causing it. Some servers sometimes return HTTP response [403](https://httpstatuses.com/403) (FORBIDDEN; The server understood the request but refuses to authorize it.). I thought it could be because some HTTP headers that browsers set are missing and the server is refusing to answer it properly. I copied all the headers my browser sends to Cronfig requests, but it didn't help either. 

I cannot replicate this issue on any of my servers, so I'd like to crowd source the possible solution here. If you have some idea what's causing it and how to fix it, please, comment bellow.

**Comment by Paul979** [comment]
Is this not directly related to the secret key issue?

This is the error message I'm getting:

HTTP status is not 2xx. That means not successful.
error: secret key is missing in the configuration

And on the second run:
error: secret key mismatch

**Comment by Paul979** [comment]
Just found a new Cronfig error in my log. Maybe that will help give some more insight into what's happening:

`[2017-02-04 05:41:25] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "cronfig" as such route does not exist." at /home/boracayc/public_html/mautic/app/cache/prod/appProdProjectContainerUrlGenerator.php line 359 {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"cronfig\" as such route does not exist. at /home/boracayc/public_html/mautic/app/cache/prod/appProdProjectContainerUrlGenerator.php:359)"} []`

**Comment by escopecz** [comment]
I believe this issue has been fixed by today's Cronfig API update. All users will get the fix automatically, no action needed from your side.
